# Generated by Django 5.2.15 on 2026-06-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDictionary',
            fields=[
                ('dictionary_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('dioula', 'Dioula'), ('bambara', 'Bambara'), ('moore', 'Mooré'), ('french', 'Français')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='dictionaries/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['language', 'title'],
                'indexes': [models.Index(fields=['language'], name='sanka_app_l_languag_c8c95a_idx')],
            },
        ),
    ]
