# Generated by Django 5.2.15 on 2026-06-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0002_localdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalArchive',
            fields=[
                ('archive_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('document_type', models.CharField(max_length=255)),
                ('provenance', models.CharField(max_length=500)),
                ('file', models.FileField(blank=True, max_length=500, null=True, upload_to='archives/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['archive_id'],
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('moderator', 'Modérateur')], default='contributor', max_length=50),
        ),
    ]
