# Generated by Django 5.2.15 on 2026-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0003_localarchive_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalAudio',
            fields=[
                ('audio_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('dioula', 'Dioula'), ('bambara', 'Bambara'), ('moore', 'Mooré'), ('french', 'Français'), ('other', 'Autre')], max_length=50)),
                ('dialect', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(max_length=500, upload_to='audios/accents/%Y/%m/%d/')),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('transcript', models.TextField(blank=True, help_text="Transcription ou informations extraites de l'audio", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['language'], name='sanka_app_l_languag_7e031c_idx')],
            },
        ),
    ]
