# Generated by Django 5.2.15 on 2026-06-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0004_localaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localaudio',
            name='file',
        ),
        migrations.AddField(
            model_name='localaudio',
            name='audio_data',
            field=models.TextField(blank=True, help_text='Données audio en Base64', null=True),
        ),
    ]
