# Generated by Django 5.2.15 on 2026-06-23 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0005_remove_localaudio_file_localaudio_audio_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreCountry',
            fields=[
                ('id_name', models.CharField(help_text='ex: burkina_faso', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('local_greeting', models.CharField(max_length=100)),
                ('local_greeting_explanation', models.TextField()),
                ('capital', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=255)),
                ('flag_emoji', models.CharField(max_length=10)),
                ('overview', models.TextField()),
                ('history', models.TextField(blank=True, null=True)),
                ('culture', models.TextField(blank=True, null=True)),
                ('gastronomy', models.TextField(blank=True, null=True)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('demographics', models.JSONField(blank=True, default=dict)),
                ('economy', models.JSONField(blank=True, default=dict)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExploreLandmark',
            fields=[
                ('landmark_id', models.CharField(help_text='ex: bk_sindou', max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('category_label', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('date_range', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='sanka_app.explorecountry')),
            ],
        ),
    ]
