# Generated by Django 5.2.15 on 2026-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0006_explorecountry_explorelandmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explorecountry',
            options={'verbose_name': "Pays (Explorer l'Afrique)", 'verbose_name_plural': "Pays (Explorer l'Afrique)"},
        ),
        migrations.AlterModelOptions(
            name='explorelandmark',
            options={'verbose_name': "Site touristique (Explorer l'Afrique)", 'verbose_name_plural': "Sites touristiques (Explorer l'Afrique)"},
        ),
    ]
