# Generated by Django 5.2.15 on 2026-06-23 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0007_alter_explorecountry_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExploreDemography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=100, null=True, verbose_name='Population totale')),
                ('density', models.CharField(blank=True, max_length=100, null=True, verbose_name='Densité')),
                ('median_age', models.CharField(blank=True, max_length=100, null=True, verbose_name='Âge médian')),
                ('urban_ratio', models.CharField(blank=True, max_length=100, null=True, verbose_name="Taux d'urbanisation")),
                ('life_expectancy', models.CharField(blank=True, max_length=100, null=True, verbose_name='Espérance de vie')),
                ('ethnic_groups', models.TextField(blank=True, help_text='Séparez les groupes par des virgules', null=True, verbose_name='Groupes ethniques')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demography', to='sanka_app.explorecountry')),
            ],
            options={
                'verbose_name': 'Démographie',
                'verbose_name_plural': 'Démographies',
            },
        ),
        migrations.CreateModel(
            name='ExploreEconomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp', models.CharField(blank=True, max_length=100, null=True, verbose_name='PIB')),
                ('gdp_growth', models.CharField(blank=True, max_length=100, null=True, verbose_name='Croissance du PIB')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='Devise')),
                ('main_sectors', models.TextField(blank=True, help_text='Séparez les secteurs par des virgules', null=True, verbose_name='Secteurs principaux')),
                ('key_exports', models.TextField(blank=True, null=True, verbose_name='Exportations majeures')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='economy_info', to='sanka_app.explorecountry')),
            ],
            options={
                'verbose_name': 'Économie',
                'verbose_name_plural': 'Économies',
            },
        ),
        migrations.CreateModel(
            name='ExploreLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la langue')),
                ('percentage', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pourcentage')),
                ('language_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type (ex: Officielle, Nationale)')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explore_languages', to='sanka_app.explorecountry')),
            ],
            options={
                'verbose_name': 'Langue parlée',
                'verbose_name_plural': 'Langues parlées',
            },
        ),
    ]
