# Generated by Django 5.2.15 on 2026-06-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0008_exploredemography_exploreeconomy_explorelanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='explorecountry',
            name='demographics',
        ),
        migrations.RemoveField(
            model_name='explorecountry',
            name='economy',
        ),
        migrations.RemoveField(
            model_name='explorecountry',
            name='languages',
        ),
    ]
