# Generated by Django 5.2.15 on 2026-06-24 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0009_remove_explorecountry_demographics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalAudio',
        ),
    ]
