# Generated by Django 5.2.15 on 2026-06-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanka_app', '0010_delete_localaudio'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorelandmark',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Histoire de ce joyau national', null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='image_1',
            field=models.URLField(blank=True, help_text='Image suppl. 1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='image_2',
            field=models.URLField(blank=True, help_text='Image suppl. 2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='image_3',
            field=models.URLField(blank=True, help_text='Image suppl. 3', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='image_4',
            field=models.URLField(blank=True, help_text='Image suppl. 4', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='image_5',
            field=models.URLField(blank=True, help_text='Image suppl. 5', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='practical_tips',
            field=models.TextField(blank=True, help_text='Conseils pratiques séparés par des sauts de ligne', null=True),
        ),
        migrations.AddField(
            model_name='explorelandmark',
            name='why_visit',
            field=models.TextField(blank=True, help_text='Pourquoi venir visiter ?', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentannotation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentprocessing',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exploredemography',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exploreeconomy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='explorelanguage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='knowledgelink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
